galaxy_info:
  author: Zhu Lijun
  description: Ansible role for capturing a VM via PowerVC to generate a deployable image
  company: IBM
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
  - name: IBM i
    versions:
    - 7.2 and later
  galaxy_tags:
  - powervc
  - ibmi