---
# tasks file for fix_repo_check_download_individual_ptfs
- name: initialize list
  set_fact:
    list: []

- name: compose list
  set_fact:
    list: "{{ list|default([]) + [{'ptf_id': ptfs_list_parm_var }] }}"
  loop: "{{ ptfs_list_parm }}"
  loop_control:
        loop_var: ptfs_list_parm_var

- name: initialize rc, check_fail_list, RecordNotFound_list, download_fail_list and download_success_list
  set_fact:
    rc: 0
    check_fail_list: []
    RecordNotFound_list: []
    download_fail_list: []
    download_success_list: []

- name: Check if individual PTFs are already in catalog
  ibm.power_ibmi.ibmi_fix_repo:
    type: "single_ptf"
    action: "find"
    parameters: "{{ list }}"
    checksum: True
  register: fix_repo_find_result
  delegate_to: "{{ repo_server }}"

- name: Print the individual PTFs information in catalog
  debug:
    var: fix_repo_find_result

- block:
    - name: compose be downloaded ptfs list
      set_fact:
        RecordNotFound_list: "{{ RecordNotFound_list | default([]) + [ fail_record ] }}"
      when: fail_record.db_record == 'FILE_NOT_FOUND' or fail_record.db_record == 'RECORD_NOT_FOUND' or fail_record.db_record == 'MATCH_NOT_FOUND'
      with_list: "{{ fix_repo_find_result.fail_list }}"
      loop_control:
        loop_var: fail_record

    - name: compose check_fail_list with error reason
      set_fact:
        check_fail_list: "{{ fix_repo_find_result.fail_list | difference( RecordNotFound_list ) }}"

    - name: Include download_individual_ptfs role to download a list of individual ptfs
      include_role:
        name: download_individual_ptfs
      vars:
        to_be_downloaded_list: "{{ RecordNotFound_list }}"
        download_server: "{{ repo_server }}"
      ignore_errors: True
      when: RecordNotFound_list != []

    - block:
        - name: Add individual ptf record into catalog
          ibm.power_ibmi.ibmi_fix_repo:
            type: "single_ptf"
            action: "add"
            checksum: True
            parameters: "{{ download_success_list }}"
          register: fix_repo_add_result
          when: download_success_list != []
          delegate_to: "{{ repo_server }}"

        # - name: Print fail_list with other errors
        #   debug:
        #     var: check_fail_list

        # - name: Print be downloaded ptfs list
        #   debug:
        #     var: RecordNotFound_list

        - name: Print fail downloadded ptfs list
          debug:
            var: download_fail_list

        - name: Print successfully downloadded ptfs list
          debug:
            var: download_success_list

      when: download_success_list != []

    - block:
        - name: Download fail
          debug:
            msg: "No ptf is successfully downloaded"
      when: download_success_list == [] and RecordNotFound_list != []

  when: fix_repo_find_result.fail_list is defined

- block:
    - name: End play when no ptf need to download
      debug:
        msg: "All ptfs are in catalog"
  when: fix_repo_find_result.fail_list is not defined

- name: Get the final result of PTFs in catalog
  ibm.power_ibmi.ibmi_fix_repo:
    type: "single_ptf"
    action: "find"
    parameters: "{{ list }}"
    checksum: True
  register: final_find_result
  delegate_to: "{{ repo_server }}"

- name: Print the final individual PTFs information in catalog
  debug:
    var: final_find_result