---
# role for sync_apply_ptf_group
# Call ibm.power_ibmi.ibmi_synchronize_files to tranfer the exists ptf group files to an ibm i system, then call ibm.power_ibmi.ibmi_fix_imgclg to apply this
# ptf group. And return the result.
- name: Initialize sync_list and sync_apply_fail
  set_fact:
    sync_list: []
    sync_apply_fail: False

- name: Compose target tmp dir str
  set_fact:
    path: "{{ dest }}/{{ ptf_group_info.file_path | basename }}"

- name: Make receive dir
  file:
    path: "{{ path }}"
    state: directory
    mode: 0755
  register: file_result
  ignore_errors: True

- block:
    - name: Skip when make receive dir fail
      debug:
        msg: "{{ 'Make receive dir ' + path + ' fail, skip the rest of this role.' }}"

    - name: Initialize sync_apply_fail
      set_fact:
        sync_apply_fail: True
  when: file_result.failed == 1

- block:
    - name: compose src_list
      set_fact:
        src_list: "{{ src_list | default([]) + [{ 'src': ptf_group_info.file_path + '/' + item }] }}"
      loop: "{{ ptf_group_info.file_name }}"

    - debug:
        var: src_list

    - name: Transfer image to target_system
      ibm.power_ibmi.ibmi_synchronize_files:
        dest: "{{ path }}"
        src_list: "{{ src_list }}"
      delegate_to: "{{ src_host }}"
      register: sync_result

    - name: Print transfer
      debug:
        var: sync_result

    - block:
        - name: skip when transfer failed
          debug:
            msg: "One or more ptf group file transfer failed, quit apply ptf group action."

        - set_fact:
            sync_apply_fail: True
      when: sync_result.fail_list != []

    - block:
        - name: Apply PTF group
          ibm.power_ibmi.ibmi_fix_imgclg:
            src: '{{ path }}'
          register: apply_result

        - name: Print apply result
          debug:
            var: apply_result
      when: sync_result.fail_list == []

  when: file_result.failed == 0
