---
# tasks file for check_ptfs_by_product
- name: fail the playbook if repo_server is invalid
  fail:
    msg: "repository server is not provided, please provide the repository server."
  when: not repo_server or repo_server is undefined

- name: fail the playbook if product is invalid
  fail:
    msg: "product is not provided, please provide the product id."
  when: not product or product is undefined

- name: initialize ptf_status
  set_fact:
    ptf_status: []

- name: query system release
  ibm.power_ibmi.ibmi_sql_query:
    sql: "SELECT OS_VERSION, OS_RELEASE FROM SYSIBMADM.ENV_SYS_INFO"
  register: result

- name: compose parameter release
  set_fact:
    release: "{{ 'V' + result['row'][0]['OS_VERSION'] + 'R' + result['row'][0]['OS_RELEASE'] + 'M0' }}"

- name: retrieve the PTF list by product from repository server
  ibm.power_ibmi.ibmi_fix_repo:
    action: "find"
    type: "single_ptf"
    parameters:
      - { 'product': '{{ product }}', 'release': '{{ release }}' }
  delegate_to: "{{ repo_server }}"
  register: product_info

- name: got record failed from repository server
  set_fact:
    ptf_status: "{{ ptf_status|default([]) + [{ 'PRODUCT': prod.product, 'PRODUCT_STATUS': 'Record not found in repository DB' }] }}"
  when: product_info.get('fail_list')
  with_list: "{{ product_info.fail_list }}"
  loop_control:
    loop_var: prod

- name: compare the ptfs on target system
  include_tasks: compare_ptf.yml
  when: product_info.get('success_list')
